language: go
go:
    - 1.7.5

script:
    - go test -v ./...
    - cd $HOME/gopath/src/github.com/JoeReid/fastTCP/examples/echoServer && go build
    - cd $HOME/gopath/src/github.com/JoeReid/fastTCP/examples/http && go build
